remote_theme: pages-themes/cayman@v0.2.0
logo: docs/assets/EEPortfolioImage.png
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: E Elizondo Portfolio Page
description: Samples of Analysis Work
